<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/151227/1-15122G44952.jpg ",93,239);
$z[1][4]['ddimg']="/uploads/allimg/151227/1-15122G44952.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="1600";
$z[1][4]['height']="900";
$z[2]=Array("img"," /uploads/allimg/151227/1-15122G45000.jpg ",241,387);
$z[2][4]['ddimg']="/uploads/allimg/151227/1-15122G45000.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="1600";
$z[2][4]['height']="900";

?>