<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/151130/1-151130112U6.jpg ",93,239);
$z[1][4]['ddimg']="/uploads/allimg/151130/1-151130112U6.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="1417";
$z[1][4]['height']="638";
$z[2]=Array("img"," /uploads/allimg/151130/1-151130112U6-50.jpg ",241,393);
$z[2][4]['ddimg']="/uploads/allimg/151130/1-151130112U6-50.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="1417";
$z[2][4]['height']="638";
$z[3]=Array("img"," /uploads/allimg/151130/1-151130112U7.png ",395,540);
$z[3][4]['ddimg']="/uploads/allimg/151130/1-151130112U7.png";
$z[3][4]['text']="";
$z[3][4]['width']="375";
$z[3][4]['height']="211";
$z[4]=Array("img"," /uploads/allimg/151130/1-151130112U7-50.png ",542,693);
$z[4][4]['ddimg']="/uploads/allimg/151130/1-151130112U7-50.png";
$z[4][4]['text']="";
$z[4][4]['width']="375";
$z[4][4]['height']="211";

?>