<li class="slide-item scrollbg pos_b proloader_img" style="background-image: url('[field:litpic/]')" data-loadimg="[field:litpic/]">
        <div class="btm_cont">
          <div class="title wrap c_white">
            <h3>Featured Project</h3>
            <hr class="title_hr">
          </div>
          <a href="[field:arcurl/]" class="info wrap">
          <div class="bg trans"></div>
          <span class="icon_after trans">查看项目详情</span>
          <div class="title">
            <h2 class="mb5 trans">[field:title/]</h2>
            <h4>[field:shorttitle/]</h4>
          </div>
          </a> </div>
      </li>