<?php
$z[0]=Array("field","",411,430);
$z[0][4]['name']="title";
$z[1]=Array("global","",431,457);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",498,520);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",560,611);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1870,1905);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",8519,8556);
$z[5][4]['filename']="footer.htm";

?>