{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/151227/1-15122G50H4.jpg' text='' width='1600' height='892'} /uploads/allimg/151227/1-15122G50H4.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/151227/1-15122G50H4-50.jpg' text='' width='1600' height='900'} /uploads/allimg/151227/1-15122G50H4-50.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/151227/1-15122G50H5.jpg' text='' width='1600' height='900'} /uploads/allimg/151227/1-15122G50H5.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/151227/1-15122G50H5-50.jpg' text='' width='1600' height='900'} /uploads/allimg/151227/1-15122G50H5-50.jpg {/dede:img}
