<?php
$z[0]=Array("global","",425,451);
$z[0][4]['name']="cfg_address";
$z[1]=Array("global","",518,540);
$z[1][4]['name']="cfg_tel";
$z[2]=Array("global","",745,767);
$z[2][4]['name']="cfg_tel";
$z[3]=Array("global","",838,862);
$z[3][4]['name']="cfg_email";
$z[4]=Array("global","",1068,1092);
$z[4][4]['name']="cfg_email";
$z[5]=Array("global","",1186,1207);
$z[5][4]['name']="cfg_qq";
$z[6]=Array("channel","\r\n      <li><a href=\"[field:typeurl/]\" class=\"trans\">[field:typename/]<br>\r\n        [field:seotitle/]</a> </li>\r\n      ",1572,1740);
$z[6][4]['type']="top";
$z[6][4]['row']="10";
$z[7]=Array("global","",1797,1823);
$z[7][4]['name']="cfg_powerby";
$z[8]=Array("global","",1902,1926);
$z[8][4]['name']="cfg_beian";
$z[9]=Array("global","",1989,2012);
$z[9][4]['name']="cfg_sina";

?>