<?php
$z[0]=Array("global","",777,803);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",847,877);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",914,941);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",2212,2247);
$z[3][4]['filename']="head.htm";
$z[4]=Array("arclist","\r\n      <li class=\"slide-item scrollbg pos_b proloader_img\" style=\"background-image: url('[field:litpic/]')\" data-loadimg=\"[field:litpic/]\">\r\n        <div class=\"btm_cont\">\r\n          <div class=\"title wrap c_white\">\r\n            <h3>Featured Project</h3>\r\n            <hr class=\"title_hr\">\r\n          </div>\r\n          <a href=\"[field:arcurl/]\" class=\"info wrap\">\r\n          <div class=\"bg trans\"></div>\r\n          <span class=\"icon_after trans\">查看项目详情</span>\r\n          <div class=\"title\">\r\n            <h2 class=\"mb5 trans\">[field:title/]</h2>\r\n            <h4>[field:shorttitle/]</h4>\r\n          </div>\r\n          </a> </div>\r\n      </li>\r\n      ",2430,3154);
$z[4][4]['titlelen']="50";
$z[4][4]['row']="1";
$z[4][4]['typeid']="2";
$z[5]=Array("arclist","\r\n        <li> <a href=\"[field:arcurl/]\" class=\"box_shadow trans\"> <img src=\"[field:litpic/]\" alt=\"\" class=\"trans\">\r\n          <div class=\"title\">\r\n            <h5 class=\"mb5 trans\">[field:title/]</h5>\r\n            <h5 class=\"hide_in_mobile trans\">[field:shorttitle/]</h5>\r\n            <hr class=\"trans\">\r\n          </div>\r\n          </a> </li>\r\n        ",4574,4988);
$z[5][4]['titlelen']="";
$z[5][4]['row']="4";
$z[5][4]['typeid']="2";
$z[6]=Array("include","",6208,6245);
$z[6][4]['filename']="footer.htm";

?>