<?php
$z[0]=Array("field","",411,430);
$z[0][4]['name']="title";
$z[1]=Array("global","",431,457);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",498,520);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",560,611);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1914,1949);
$z[4][4]['filename']="head.htm";
$z[5]=Array("arclist","\r\n          <li><a class=\"btn_white icon-head box_shadow trans\">[field:title/]</a></li>\r\n          ",3887,4045);
$z[5][4]['titlelen']="";
$z[5][4]['row']="8";
$z[5][4]['typeid']="";
$z[6]=Array("global","",4115,4139);
$z[6][4]['name']="cfg_email";
$z[7]=Array("global","",4174,4198);
$z[7][4]['name']="cfg_email";
$z[8]=Array("global","",4216,4238);
$z[8][4]['name']="cfg_tel";
$z[9]=Array("global","",4274,4296);
$z[9][4]['name']="cfg_tel";
$z[10]=Array("global","",4804,4828);
$z[10][4]['name']="cfg_email";
$z[11]=Array("global","",4863,4887);
$z[11][4]['name']="cfg_email";
$z[12]=Array("global","",4953,4975);
$z[12][4]['name']="cfg_tel";
$z[13]=Array("list","\r\n          <li class=\"item\">\r\n            <h3 class=\"c_red\">[field:title/]</h3>\r\n            [field:body/] </li>\r\n          ",5279,5441);
$z[13][4]['pagesize']="12";
$z[14]=Array("include","",16552,16589);
$z[14][4]['filename']="footer.htm";

?>