<?php
$z[0]=Array("field","",411,430);
$z[0][4]['name']="title";
$z[1]=Array("global","",431,457);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",498,520);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",560,611);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1870,1905);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",2084,2138);
$z[5][4]['name']="typeid";
$z[5][4]['function']="GetTopimg(@me)";
$z[6]=Array("field","",2170,2224);
$z[6][4]['name']="typeid";
$z[6][4]['function']="GetTopimg(@me)";
$z[7]=Array("list","\r\n<section id=\"s1\" class=\"desktop_full mscroll\">\r\n  <div class=\"full scrollbg pos_b anima_3d_top\" style=\"background-image: url('[field:litpic/]')\"> </div>\r\n  <div class=\"btm_cont anima_3d_bottom b_to_t\">\r\n    <div class=\"title wrap c_white r_to_l\">\r\n      <h2>[field:title/]</h2>\r\n      <h3>[field:shorttitle/]</h3>\r\n      <hr class=\"title_hr\">\r\n    </div>\r\n    <div class=\"info pmt0 wrap\">\r\n      <p>[field:description function='cn_substr(@me,180)'/]</p>\r\n      <div id=\"hideobj-1\" class=\"clearfix collapse\" aria-expanded=\"false\" style=\"height: 0px;\">[field:body/]</div>\r\n      <a href=\"#hideobj-1\" data-toggle=\"collapse\" aria-expanded=\"false\" aria-controls=\"hideobj-1\" class=\"btn_red btn_more trans collapsed\"> <span class=\"more trans\">MORE +</span> <span class=\"less trans\">LESS -</span> </a> </div>\r\n  </div>\r\n</section>\r\n",2742,3605);
$z[7][4]['pagesize']="12";
$z[8]=Array("include","",3842,3879);
$z[8][4]['filename']="footer.htm";

?>