<?php  exit();
/*
Page: /dede/makehtml_all.php?action=make&step=3&uptype=mkall&mkvalue=0
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'LIMIT 0,1' at line 1 <br />Error sql: <font color='red'>SELECT seotitle FROM dede_arctype WHERE id= LIMIT 0,1;</font>
Time2017-12-19 16:54:01
*/
?>
<?php  exit();
/*
Page: /dede/makehtml_homepage.php?dopost=view&templet={style}/index.htm
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'LIMIT 0,1' at line 1 <br />Error sql: <font color='red'>SELECT seotitle FROM dede_arctype WHERE id= LIMIT 0,1;</font>
Time2017-12-19 16:54:08
*/
?>
